env:
  browser: true
  es2021: true
  jquery: true
extends:
  - 'eslint:recommended' 
  - 'plugin:@typescript-eslint/eslint-recommended',
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  max-len:
      - error
      -
        code: 80
  indent:
    - error
    - 2
    -
      FunctionExpression:
        parameters: 'first'
        body: 1
      FunctionDeclaration:
        parameters: 'first'
        body: 1
      CallExpression:
        arguments: 'first'
      MemberExpression: 1
      VariableDeclarator: 'first'
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  class-methods-use-this:
    - error
  eqeqeq:
    - error
    - smart
  no-fallthrough:
    - error
  no-unused-vars:
    - error
    -
      vars: 'all'
      args: 'after-used'
      varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  "@typescript-eslint/no-unused-vars":
    - error
    -
      vars: 'all'
      args: 'after-used'
      varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'

